<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ page.title }}</title>
  <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
  <!-- Header Section -->
  <header>
    <div class="container">
      <h1>{{ site.title }}</h1>
      <h2>{{ site.description }}</h2>
      <nav>
        <ul>
          {% for item in site.navigation %}
            <li><a href="{{ item.link }}">{{ item.name }}</a></li>
          {% endfor %}
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Content Section -->
  <main>
    <div class="container">
      {{ content }}
    </div>
  </main>

  <!-- Footer Section -->
  <footer>
    <div class="container">
      <p>&copy; {{ site.author.name }} - {{ site.author.email }}</p>
      <p>"A journey of a thousand miles begins with a single step" - Lao Tzu</p>
    </div>
  </footer>
</body>
</html>
